### ISSUE TITLE
Umgang mit WP_DEBUG/Admin Notices verbessern

### ISSUE THREAD

**Issue by alpipego** [hesstobi/herrnhuter-losung-widget#10]
Die Fehlermeldungen im XML-Updater https://github.com/hesstobi/herrnhuter-losung-widget/blob/master/lib/xmlfilereader.php#L62-L64 und https://github.com/hesstobi/herrnhuter-losung-widget/blob/master/lib/xml_automatic_updater.php#L134-L135 sollten m.E. nicht von `WP_DEBUG` abhängig sein, sondern als Admin Notices bzw. Errors ausgespielt werden.

**Comment by benjaminpick** [comment]
Ja, du hast Recht, Admin Messages wären schöner - soviel Arbeit hatte ich mir da nicht gemacht. Wenn du möchtest kannst du dafür gerne ein PR machen.
