### ISSUE TITLE
Komischer Fehler: Konnte keine Losungsverse für diesen Tag finden.

### ISSUE THREAD

**Issue by b6r** [hesstobi/herrnhuter-losung-widget#11]
Hi,
habe das Plugin in der Version 1.7.3 in einem Wordpress 4.7.2 installiert und aktiviert. Die aktuelle Losungsdatei losungen2017.xml liegt im plugin-Verzeichnis. Trotzdem bekomme ich den o.g. Fehler. Habe mal ein bisschen im Code rumgesucht (mein PHP ist ziemlich verstaubt) und habe zumindest heraus gefunden, dass das Plugin die Datei findet, aber halt keine aktuelle Losung im xml-Objekt finden kann ($xml ist false).

Ich gehe im Moment von einem Layer-8-Problem aus. Hilfe wäre trotzdem nett.

Dank und Gruß
Jochen

**Comment by obstschale** [comment]
Hast du die neuste Version hier aus dem Repo installiert oder eine ältere Version?

Du sagst `$xml` sei `false`. In welcher Datei/Zeile ist das?

**Comment by benjaminpick** [comment]
Vielleicht funktioniert SimpleXML nicht? Das ist aber eigentlich nur bei
PHP 5.2 oder früher der Fall.

Benjamin

**Comment by obstschale** [comment]
> Vielleicht funktioniert SimpleXML nicht? Das ist aber eigentlich nur bei PHP 5.2 oder früher der Fall.

Dann sollten die Requirements in der README geändert werden dort steht:

> Voraussetzungen
>
>    Wordpress > 2.8
>    PHP > 5.0

**Comment by benjaminpick** [comment]
Oh, hatte ich falsch im Kopf, PHP >= 5.0 ist korrekt.

Am 30.01.2017 um 17:43 schrieb Hans-Helge Buerger:

**Comment by b6r** [comment]
So, jetzt bin ich endlich wieder online. Danke erstmal für deine Antworten.
Das $xml false ist, hatte ich mal kurz im Code abgefragt und daraufhin eine Exception geschmissen (nach Zeile 67). Ja, es sieht so aus, als ob SimpleXML nicht so tun will wie gedacht. Mhm. Vlt. muss ich das auch noch einmal auf einer anderen Installation nachstellen. 

btw: PHP ist in Version 5.6.21.

**Comment by b6r** [comment]
Die Losungen werden wieder angezeigt. Ich hatte, aus welchem Grund auch immer, die Losungsdatei auch noch in den uploads-Ordner kopiert. Als ich sie im plugin-Verzeichnis gelöscht hatte, wurden die Losungen wieder angezeigt. Nachstellen lies es sich aber nicht mehr. Warum auch immer. 
Egal. Das Ergebnis zählt. Danke für die Arbeit und das Widget.
