### ISSUE TITLE
Herrnhuter Tageslosung ohne Lehrtext?

### ISSUE THREAD

**Issue by c-davidson** [hesstobi/herrnhuter-losung-widget#12]
Wir sind auf der Suche nach einem Plugin für Wordpress mit nur der Herrnhuter Tageslosung, also ohne den Lehrtext. Können Sie uns weiterhelfen?

**Comment by hesstobi** [comment]
Laut Nutzungsbedingungen der Herrnhuter Losungen ist dies nicht zulässig. Siehe https://www.losungen.de/download/nutzungsbedingungen/

> 2. Die Anzeige der Losungstexte besteht immer aus beiden Bibelversen, dem alttestamentlichen Text (der Losungsvers) und dem neutestamentlichen Vers (dem Lehrtext).

Also nein, ich kann ihnen nicht helfen.
