### ISSUE TITLE
Losung RSS Feed

### ISSUE THREAD

**Issue by obstschale** [hesstobi/herrnhuter-losung-widget#2]
Ich steige selber erst ein in die WordPress Programmierung und habe vor dieses Plugin etwas auszubauen. Deshalb möchte ich nicht meinen eigenen Versuch weiter ausbauen ([LosungWP](https://github.com/obstschale/LosungWP)) sondern möchte dieses Plugin weiter ausbauen.

Auf der Losungs Webpage habe ich einen RSS Feed gefunden mit der täglichen Losung ([Losung Feed](http://www.hradetzkys.de/rss/tageslosung.xml)) wäre, dass nicht eine alternative zum manuellen hochladen des XML Files?

**Comment by tyrann0us** [comment]
BTW, the RSS feed URL mentioned in the issue description no longer works: http://www.hradetzkys.de/rss/tageslosung.xml.
It might make sense to close this ancient issue.
