### ISSUE TITLE
Losungen 2015 xml-file hinterlegen

### ISSUE THREAD

**Issue by snowlord78** [hesstobi/herrnhuter-losung-widget#4]
Hallo,

hatte mir die neue Version 1.7 aufegespielt, jedoch funktioniert im Widget die Update Funktion nicht. Habe dann die aktuelle xml-Datei unter losungen.de runtergeladen, entpackt und in losungen2015.xml umbenannt. Danach habe ich diese in das Plugin Verzeichnis, wo die losungen2014.xml liegt, hineinkopiert und die alte losungen2014.xml gelöscht.
Ich wollte euch darüber informieren und fände es nicht schlecht, wenn die losungen2015.xml hier ins Github eingepflegt wird und man es dann automatisch in der zip-Datei mit drin hat, denn es gibt vielleicht auch andere Leute, die das Problem haben und nicht auf die Idee kommen bzw. kamen und dann aus Frust das Plugin wieder deinstallieren. Das finde ich persönlich nicht so toll, da ich das Plugin gut finde und es sich wunderbar auf unserer Homepage macht. Auf diesem Wege noch einmal vielen Dank dafür.

Snowlord

**Comment by benjaminpick** [comment]
Ja ich hab das auch gerade festgestellt, tut mir leid für den Ärger - bei Version 1.7.1 funktioniert es jetzt. Ja ich kann die XML hier auch hinterlegen, ich möchte nur nicht jährlich eine neue Version herausgeben müssen.
