### ISSUE TITLE
"Umgebung" nicht von WP_DEBUG abhängig machen

### ISSUE THREAD

**Issue by alpipego** [hesstobi/herrnhuter-losung-widget#9]
In https://github.com/hesstobi/herrnhuter-losung-widget/blob/master/lib/xml_automatic_updater.php#L46-L53 ist die Umgebung von `WP_DEBUG` abhängig, was dazu führt, dass auf meiner Seite das automatische Update nicht funktioniert.

## Mögliche Lösung
Ich schlage vor hier die Konstante `WP_ENV` (roots/bedrock framework) zur Identifizierung der Umgebung zu nutzen:

```
	protected function _getDownloadUrl($date)
	{
		if (defined('WP_ENV') && WP_ENV === 'development')
			$url = 'http://localhost/local/Losung_%s_XML.zip';
		else
			$url = apply_filters('herrnhuterlosung_download_url', self::DOWNLOAD_URL);
		return sprintf($url, (int) $date['year']);	
	}
```

Gerne erstelle ich auch einen PR für die Änderung.

**Comment by benjaminpick** [comment]
Ja, du hast Recht, `WP_DEBUG` könnte auch auf einem Produktivsystem Sinn machen (z.B. in Verbindung mit `WP_DEBUG_LOG`). 

Aber haben wir bei WP_ENV nicht das gleiche Problem, dass wir hier eine Verwendung vorraussetzen die nicht unbedingt so sein muss? Meine Tendenz wäre eher die Zeile mit dem Localhost auszukommentieren, man könnte sie ja über den Filter immer noch realisieren ... Was meinst du, @hesstobi ?
